version: '3.4'
services:
  server:
    build:
      context: ./
      target: dev
    volumes:
      - .:/app
    command: yarn run dev
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  server-prod:
    build:
      context: ./
      target: prod
    volumes:
      - .:/app
    command: yarn run prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # DEBUG: nodejs-docker-express:*
  