name: deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # Everyday at 12am
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

#       - run: npm install
#       - run: npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

#       - name: Deploy with rsync
#         run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/223etsk.ru/

      - name: Restart Node Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: >
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcnNhAAAAAwEAAQAAAgEAvk/KvOvJ2Pl4JTg4Y4vpxdYDoWO8Ts7KQnwuGNaB3+UVaIJuDGNUJq9nt2+rhfvyyCTP8I6u3akH9XgtEJV0/HbwDAOLVTeN9ynzZ5u2Vh3g/XFT4G5IOflTURgGsAWk0tQh4ZdGNMlkdTVUyhg0JVyfLqLyKqcmO8XH41c9is2WQmObIZmGkpi+XgwCNxrhpCo8kdcW9vSeHANqmrpxM/HqNks4TFX6fmnUrrERwGbvu5aPXuCBCf9nESjJzpxN3hwebVDxod796CvsGUiM/oPXzCAL+UuQjZXh+oNTjLQQotAxCsuR3RLtiilWjcl1zrdgYxFcMZwK0GkwUfjnLpWbmJ2RBD0QBEf0GiD0aH5GsoDDKaLR1B4uB4UePXNLroXqMgvBIF5eGyj1ng21x87e4HIW5ZRrQrsVtbR/7oZZFYhS4Jbp2OlZXcSePUyALj4oQfZ79jRHT5yGxj82Fd1T9OtGfuiwEWdJTeJAzyIQa+yZYNTJnl+MPAy+pvXJJ2vlB/1fD8/vwqv3+RMgxjdX1fKE9s+mkD8FhjnndFNfP4uH8vENlY4VF+NyYOvK2T0Ft43cjyybQXwZ9YBAJMFeSjn8UBxiyGS07LH50Xs/9wJuw3UIPP5Obc6yITXTUJZG5k3Z7MxeNGxWJdg82EhX0DioNcGBvC0u18svPFEAAAdQplGgH6ZRoB8AAAAHc3NoLXJzYQAAAgEAvk/KvOvJ2Pl4JTg4Y4vpxdYDoWO8Ts7KQnwuGNaB3+UVaIJuDGNUJq9nt2+rhfvyyCTP8I6u3akH9XgtEJV0/HbwDAOLVTeN9ynzZ5u2Vh3g/XFT4G5IOflTURgGsAWk0tQh4ZdGNMlkdTVUyhg0JVyfLqLyKqcmO8XH41c9is2WQmObIZmGkpi+XgwCNxrhpCo8kdcW9vSeHANqmrpxM/HqNks4TFX6fmnUrrERwGbvu5aPXuCBCf9nESjJzpxN3hwebVDxod796CvsGUiM/oPXzCAL+UuQjZXh+oNTjLQQotAxCsuR3RLtiilWjcl1zrdgYxFcMZwK0GkwUfjnLpWbmJ2RBD0QBEf0GiD0aH5GsoDDKaLR1B4uB4UePXNLroXqMgvBIF5eGyj1ng21x87e4HIW5ZRrQrsVtbR/7oZZFYhS4Jbp2OlZXcSePUyALj4oQfZ79jRHT5yGxj82Fd1T9OtGfuiwEWdJTeJAzyIQa+yZYNTJnl+MPAy+pvXJJ2vlB/1fD8/vwqv3+RMgxjdX1fKE9s+mkD8FhjnndFNfP4uH8vENlY4VF+NyYOvK2T0Ft43cjyybQXwZ9YBAJMFeSjn8UBxiyGS07LH50Xs/9wJuw3UIPP5Obc6yITXTUJZG5k3Z7MxeNGxWJdg82EhX0DioNcGBvC0u18svPFEAAAADAQABAAACAQC8g6GZ3h7FlOhURgplYTSiScqy1W60ydZEYWnwJJvlwrCgI4MLNmEnKN0eMbnAMMBfTUfFTDEfVM6TcwWAxetqIg7Kd8BPG4a+7Ik1emL1jwdNRjMFv3hAJR9I1vnY5t5MEOG26vgaVdvy1m80+SC+Wa88rSAg7A3Na68DHWnS0q8i+DO05rUNBcycsFyJZVFaIpR5Coyu98SejyvMNR7pi5qrSXts8kX9bqvEl5Wz9sNGGG/QVaa81oer0bGFvgLMHyJsup9/7rmof8mRifJQMx1SD/SMbzOzbGK6mdfrKnrILF5ICTpluNgf4a7hKExQBgmuWIXwhleX9nps2Jd2MAvt6juq9wPJZLnZwwz7VTzMmjiW1w+UQTSarBXpet532P9O14thFZSuR7eyuaPqJ/08wfyjId01mxTzTT68UfKZJg5m3xZTYlAH7INkmX5reOVrph6thgflV3vRqHwtqVef9diTiNIjEQVW7BHKrNJ4w3hQGDVrdKtczJuXfYyLBzKXt0k2M5cnZmyWDLmU4g3DHB5NWh0EZ7oDdhWxmzh24YUeg+UinmeQTxXvomk7ZGyhjLROBqLyrSR4ZjKl9kV3SF47Bv5Stq6iWHC2/XS/02kOIo7x0dO9prq4ZmVgZQkxKAH+C9/TeRFZHqbAZhfEFw7MuYRyBAjRUWfweQAAAQEAuqcGIcZvOGs+PEXYcfMfs7Z4PfTRHHZlB9I1xKEH6+AETqSrzFvBvMmTqrFbTcmzd09gF3cokmESlfwo0edUw9xFRh6jU+bgyvB8/EWAIAmgYdTEwMNW4+LL188DVZDhiAbdrjhUwksgJSVFHc29k7OJ27xuLKs8MDay+vL26WoCiaoetHrWOePBzksbIseShmfDR683upWYviuwMzzbgFimUX46UEKHK8m/Ol46Zc2i6WcE8yIn8Q0jeAV/s2dQ8KshAVAnnOY/9w/h6TEixmy3i5J21MxJtClU5sgKvbTOAR6GlC02eEQrQjPCHKAqUFRqkj2NpsTeKaeSqtmeiQAAAQEA9Ng9IFUseLhbDqVrN9yIvRkuU+1jP3E1vjPYPxCd/lPAGDen/wDzKR6MF3vrfia5J+D5fMdv1m9iL/8PNZZn3pTeJLeu84s8sxFhXTXPsIugjnTzBokaoe5kvOofr7L+Yu8L9PC3NbdikJYh7KPwFVgrLoC6PAno0s7SrpTd5jpBHU5g7myOrY7l0+eD/MXpxXjyX4o3U8emQ4UobCyulHYLsHsUDQpXZbmE0VWRxpdqjgDzx4Ew0CGgPVe8AmAm6hFqszdm1hOGxTRpa0PDXNtRO8ZvpKrdmjHmXCculQgIHLY5fAwU8gEbnvNIhfuR87rrPrQVkqPhCuo8/erZ+wAAAQEAxvuBEcrj5O+Xlje7A2ioY0zBwHb4dpyh78qASO37gmhtSHeBs78X9wGJe5flBAWQ8Z6qTalZn5oxQaTLQXUiHFzEj8A2EpXlM9ixgAqT75dv7o4msUEvAxGdXyNYlPZpuWvGOwUNb+0pIsZqeR2dGOR98+uCDgNG/8ZLV7XRAZkqg4DFUh++3JcIoC2O3UVtF2vkzhH8G86kLkB2WOGJouN78xrw0kjLjCRG3X+MyqwF/qLxp8ezJjestlnH0MkYaIQBD+Rr8oms8ZNLlzVR6eIldLmoGjqbFXEOBO/7ZtulLvT6xMc/4aDCzODRMPkO8hDUq8R9Z5egDy2wIIYdIwAAABlib2dhdHlyb3YyMDA0ODhAZ21haWwuY29t
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/223etsk.ru
            git fetch origin master
            git reset --hard FETCH_HEAD
            git clean -d -f --exclude secrets
            npm run server:prod
            chown $(whoami) . # PM2 doesn't recognize root user from Github Actions
            # npm run restart
